moives/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("movies.urls")),
]

movies/urls.py
from django.urls import path
from . import views


app_name = "movies"

urlpatterns = [
    path("", views.main, name="main"),
    path("index/", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
]

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=20)
    grade = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ("title", "content", "movie_name", "grade")
        labels = {
            "title": "리뷰 제목",
            "content": "리뷰 내용",
            "movie_name": "영화 이름",
            "grade": "영화 평점",
        }

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.


def main(request):
    return render(request, "movies/main.html")


def index(request):
    movies = Movie.objects.all()
    context = {"movies": movies}

    return render(request, "movies/index.html", context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)

    context = {"movie": movie}

    return render(request, "movies/detail.html", context)


def delete(request, pk):
    Movie.objects.get(pk=pk).delete()
    return redirect("movies:index")


def create(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:index")
    else:
        form = MovieForm()
    context = {"form": form}
    return render(request, "movies/create.html", context=context)


def update(request, pk):
    movie = Movie.objects.get(pk=pk)

    if request.method == "POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect("movies:detail", movie.pk)

    else:
        form = MovieForm(instance=movie)
    context = {"form": form}

    return render(request, "movies/update.html", context)

movies/templates/movies/create.html
{% extends 'base.html' %}
{% block content %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

  <div class="container">


    
    <form action="{% url 'movies:create' %}" method="POST">
      {% csrf_token %}

      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" class="btn btn-dark" content="작성"%}
    </form>

  </div>

{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}

  <p>{{movie.title}}</p>
  <p>{{movie.content}}</p>
  <p>{{movie.movie_name}}</p>
  <p>{{movie.grade}}</p>

    <a href="{% url 'movies:update' movie.pk%}">수정 </a>

    <a href="{% url 'movies:delete' movie.pk %}">삭제</a>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
  <div class="row">
{% for movie in movies %}
    <div class="col-4 g-2">

      <div class="card " style="width: 18rem;">
      <img class="card-img-top" src="{% static 'images/kuromibg.png'%}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.content}}</p>
        <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-dark">리뷰 보기</a>
      </div>
    </div>

    </div>
    {% endfor %}
  </div>
</div>


{% endblock %}

movies/templates/movies/main.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
  {% load static %}
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/범죄도시2.jpeg'%}" class="d-block w-100 img-fluid" alt="범죄도시2">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Some representative placeholder content for the first slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/수리남.jpeg'%}" class="d-block w-100" alt="수리남">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Some representative placeholder content for the second slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/인터스텔라.jpeg'%}" class="d-block w-100" alt="인터스텔라">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/promise.png'%}" class="d-block w-100" alt="고백">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/train.png'%}" class="d-block w-100" alt="불렛트레인">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock %}

movies/templates/movies/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
{% block content %}

  <!-- 목록 작성 -->
  <div class="container">
    <form action="" method="POST">

      {%csrf_token%}

      {%bootstrap_form form %}

      
      {% bootstrap_button "수정" button_type="submit" button_class="btn-primary" %}

    </form>
  </div>

{% endblock %}

templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <span class="navbar-brand" href="#">
          <img src="{% static 'images/kuromi.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
          <a href="{% url 'movies:main' %}"class="text-decoration-none text-muted"><span>kuromi theater</span></a>
        </span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{% url 'movies:index' %}">리뷰 목록</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'movies:create'%}">리뷰 작성</a>
            </li>

          </ul>

        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}

    <footer class="text-center mt-5">
      Django PJT, by 문경욱, 이호빈, 권건희
    </footer>
  </body>

</html>